# Dockerfile.test
FROM python:3.11-slim

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip \
 && pip install -r requirements.txt \
 && pip install pytest

CMD ["pytest", "tests/test_nodes.py", "-v"]